### ISSUE TITLE
Depreciation Warning

### ISSUE THREAD

**Issue by deanditton** [JackStouffer/cookiecutter-Flask-Foundation#1]
In forms.py TextFeild is about be depreciate with Flask-WTF 3.0 quick change to StringField and appropriate import is all that is needed. 

Just thought you would like to know.

**Comment by JackStouffer** [comment]
Thanks for the heads up; I will fix this this weekend.

**Comment by JackStouffer** [comment]
I apologize for forgetting about this. This was fixed by 152dba0
