### ISSUE TITLE
`object_name` and `env` may be a duplicate in application factory.

### ISSUE THREAD

**Issue by qria** [JackStouffer/cookiecutter-Flask-Foundation#4]
First of all, thanks for making this project. We're using it on our site and we're loving it.

We've removed `env` argument in `create_app` to simplify the architecture and because we saw no use case that setting `env` can handle but setting config object can't handle.

In the worst case I can make different Config object that sets app.config['ENV'].

Is there a reason for having two arguments that sets configuration?

**Comment by JackStouffer** [comment]
> Is there a reason for having two arguments that sets configuration?

Originally, before I made the github project, I think (this was almost four years ago now so I'm not sure) it was a micro optimization so I didn't have to make multiple `os.environ` calls. I've removed the code that needed that from the repo before I made the separate flask foundation repo, and so the extra argument is a remnant of that.

I'll remove it. Thanks for brining it to my attention.

**Comment by JackStouffer** [comment]
Fixed via a705767
